config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	root 'pages#welcome'
	
	get 'portfolio' => 'pages#portfolio'
	
	get 'about' => 'pages#about'
	
	get 'contacts' => 'pages#contacts'
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def welcome
	end
	
	def portfolio
	end
	
	def about
	end
	
	def contacts
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,500,500i,700,700i" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="pages.css" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	
	<nav class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
		  <div class="navbar-header">
		    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
		    <%= link_to "Lorenzo C.", root_path, class: "navbar-brand" %>
		  </div>
		  <div id="navbar" class="navbar-collapse collapse">
		    <ul class="nav navbar-nav navbar-right">
		      <li> <%= link_to "Home", root_path %> </li>
		      <li> <%= link_to "Porfolio", portfolio_path %> </li>
		      <li> <%= link_to "About", about_path %> </li>
			  <li> <%= link_to "Blog", "https://medium.freecodecamp.org" %> </li>
		      <li> <%= link_to "Contacts", contacts_path %> </li>
		    </ul>
		  </div><!--/.nav-collapse -->
		</div><!--/.container(-fluid) -->
	</nav>

    <%= yield %>
	
	<footer>
		<div class="container">
			<div class="col-md-12">
				<h2>Very reserved info...</h2>
				<p>Cras quis nulla commodo, aliquam lectus sed, blandit augue. Cras ullamcorper bibendum bibendum. Duis tincidunt urna non pretium porta. Nam condimentum vitae ligula vel ornare. Phasellus at semper turpis. Nunc eu tellus tortor. Etiam at condimentum nisl, vitae sagittis orci. Donec id dignissim nunc. Donec elit ante, eleifend a dolor et, venenatis facilisis dolor. In feugiat orci odio, sed lacinia sem elementum quis. Aliquam consectetur, eros et vulputate euismod, nunc leo tempor lacus, ac rhoncus neque eros nec lacus. Cras lobortis molestie faucibus.</p>
			</div>
		</div>
		<div></div>
	</footer>
	
  </body>
</html>

<!-- TEST -->

app/views/pages/about.html.erb
<div class="jumbotron col-md-12">
	<div class="container">
		<h1>Hey, it's me!</h1>
	</div>
</div>

<div class="container">
	<div class="col-md-3">
		<img class="img-responsive" src="https://dl.dropboxusercontent.com/s/jdx1m5laarn074l/LC2.png" alt="Immagine">
	</div>
	<div class="col-md-9">
		<h2>Lorenzo C.</h2>
		<p>Cras quis nulla commodo, aliquam lectus sed, blandit augue. Cras ullamcorper bibendum bibendum. Duis tincidunt urna non pretium porta. Nam condimentum vitae ligula vel ornare. Phasellus at semper turpis. Nunc eu tellus tortor. Etiam at condimentum nisl, vitae sagittis orci. Donec id dignissim nunc. Donec elit ante, eleifend a dolor et, venenatis facilisis dolor. In feugiat orci odio, sed lacinia sem elementum quis. Aliquam consectetur, eros et vulputate euismod, nunc leo tempor lacus, ac rhoncus neque eros nec lacus. Cras lobortis molestie faucibus.</p>
	</div>
	
</div>

app/views/pages/contacts.html.erb
<div class="jumbotron col-md-12">
	<div class="container">
		<h1>Contact me!</h1>
	</div>
</div>

<div class="container">
	<div class="col-md-9">
		<p>Telefono: 123 456 789012</p>
		<p>Email: lorenzo@lorenzo.com</p>
	</div>
	
</div>

app/views/pages/portfolio.html.erb
<div class="jumbotron col-md-12">
	<div class="container">
		<h1>My portfolio!</h1>
	</div>
</div>

<div class="container">
	<div class="col-md-4">
		<img class="img-responsive" src="https://dl.dropboxusercontent.com/s/lilo1x8x9in5zlo/Screenshot%202018-04-19%2016.34.46.png" alt="Immagine">
		<p>Lorem ipsulm dolor sit amet, consectuetur adiscipit.</p>
	</div>
	<div class="col-md-4">
		<img class="img-responsive" src="https://dl.dropboxusercontent.com/s/nnbloe943ft3ap0/Screenshot%202018-04-19%2012.09.33.png" alt="Immagine">
		<p>Lorem ipsulm dolor sit amet, consectuetur adiscipit.</p>
	</div>
	<div class="col-md-4">
		<img class="img-responsive" src="https://dl.dropboxusercontent.com/s/zne4vv75doqgy5n/Screenshot%202018-04-17%2014.00.23.png" alt="Immagine">
		<p>Lorem ipsulm dolor sit amet, consectuetur adiscipit.</p>
	</div>
	<div class="col-md-4">
		<img class="img-responsive" src="https://dl.dropboxusercontent.com/s/maz3d6axymqfjru/Screenshot%202018-04-13%2018.51.12.png" alt="Immagine">
		<p>Lorem ipsulm dolor sit amet, consectuetur adiscipit.</p>
	</div>
	<div class="col-md-4">
		<img class="img-responsive" src="https://dl.dropboxusercontent.com/s/5a3e0jusoen6u5e/Screenshot%202018-04-12%2010.09.35.png" alt="Immagine">
		<p>Lorem ipsulm dolor sit amet, consectuetur adiscipit.</p>
	</div>
	<div class="col-md-4">
		<img class="img-responsive" src="https://dl.dropboxusercontent.com/s/rzu935f538iv1nz/Screenshot%202018-03-22%2014.16.55.png" alt="Immagine">
		<p>Lorem ipsulm dolor sit amet, consectuetur adiscipit.</p>
	</div>
</div>

app/views/pages/welcome.html.erb
<div class="jumbotron col-md-12">
	<div class="container">
		<h1>Tutto quello che avreste voluto sapere ma non avete mai osato chiedere!</h1>
		<a href="#" class="btn btn-primary">Show more</a>
	</div>
</div>